name: iptv_flutter
description: IPTV app with advanced media_kit player.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # API Connection
  http: ^1.1.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Advanced Player (MKV, H265, Subtitles, Audio Tracks)
  media_kit: ^1.1.10
  media_kit_video: ^1.2.1
  media_kit_libs_video: ^1.0.5
  
  # Icons and Styling
  font_awesome_flutter: ^10.6.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 # flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  # IMPORTANT: Create assets/fonts folder and place Cairo font files here.
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
